let sim_inventory = [
  {
    id: 1,
    productLine: "ALS Simulator",
    productName: "ALS Simulator (L) Manikin Only",
    serialNumber: "205M27100009",
    assetName: "205M27100009-ALS Simulator (L) Manikin Only",
    accountName: "Saint Joseph’s University",
    purchaseDate: "2010-06-25",
    installDate: "2010-07-14",
    assetWarrantyExpirationDate: "2011-07-13",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: "Room 2152 OR / Caridac",
    image: "inven_1.jpg",
  },
  {
    id: 2,
    productLine: "ALS Simulator",
    productName: "ALS Simulator (L) Manikin Only",
    serialNumber: "205M27100010",
    assetName: "205M27100010-ALS Simulator (L) Manikin Only",
    accountName: "Saint Joseph’s University",
    purchaseDate: "2010-06-25",
    installDate: "2010-07-14",
    assetWarrantyExpirationDate: "2011-07-13",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: "Room 2370 Clinical Education",
    image: "inven_2.jpg",
  },
  {
    id: 3,
    productLine: "ALS Simulator",
    productName: "ALS Simulator (L) Manikin Only",
    serialNumber: "205M52100013",
    assetName: "205M52100013-ALS Simulator (L) Manikin Only",
    accountName: "Saint Joseph’s University",
    purchaseDate: "2010-12-15",
    installDate: "2010-12-31",
    assetWarrantyExpirationDate: "2011-12-30",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: "Room 2150 Respiratory Therapy",
    image: "inven_3.jpg",
  },
  {
    id: 4,
    productLine: "ALS Simulator",
    productName: "ALS Simulator (L) Manikin Only",
    serialNumber: "205M30080019",
    assetName: "205M30080019-ALS Simulator (L) Manikin Only",
    accountName: "Saint Joseph’s University",
    purchaseDate: "2008-07-11",
    installDate: "2008-07-12",
    assetWarrantyExpirationDate: "2009-07-11",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: ""
  },
  {
    id: 5,
    productLine: "ALS Simulator",
    productName: "ALS Simulator (L) Manikin Only",
    serialNumber: "205M04090009",
    assetName: "205M04090009-ALS Simulator (L) Manikin Only",
    accountName: "Saint Joseph’s University",
    purchaseDate: "2009-01-07",
    installDate: "2009-01-08",
    assetWarrantyExpirationDate: "2010-01-07",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: "Room 2150 Respiratory Therapy",
    image: "inven_5.jpg",
  },
  {
    id: 6,
    productLine: "ALS Simulator",
    productName: "ALS Simulator (L) Manikin Only",
    serialNumber: "205M04090010",
    assetName: "205M04090010-ALS Simulator (L) Manikin Only",
    accountName: "Saint Joseph’s University",
    purchaseDate: "2009-01-07",
    installDate: "2009-01-08",
    assetWarrantyExpirationDate: "2010-01-07",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: "Room 2101 IT Storage",
    image: "inven_6.jpg",
  },
  {
    id: 7,
    productLine: "ALS Simulator",
    productName: "ALS Simulator (L) Manikin Only",
    serialNumber: "205M31080017",
    assetName: "205M31080017-ALS Simulator (L) Manikin Only",
    accountName: "Saint Joseph’s University",
    purchaseDate: "2008-08-01",
    installDate: "2013-03-18",
    assetWarrantyExpirationDate: "2014-03-17",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: ""
  },

  {
    id: 8,
    productLine: "Birthing models",
    productName: "Fundus Skills and Assessment Trainer (L)",
    serialNumber: "375MTS3822065",
    assetName: "375MTS3822065-Fundus Skills and Assessment Trainer (L)",
    accountName: "Saint Joseph’s University",
    purchaseDate: "2023-02-02",
    installDate: "",
    assetWarrantyExpirationDate: "2024-02-02",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: ""
  },

  {
    id: 9,
    productLine: "Laerdal Suction Unit",
    productName: "LSU with Bemis Canister",
    serialNumber: "78331693815",
    assetName: "78331693815-LSU with Bemis Canister",
    accountName: "Saint Joseph’s University",
    purchaseDate: "2016-10-07",
    installDate: "2016-11-10",
    assetWarrantyExpirationDate: "2021-11-09",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: ""
  },

  {
    id: 10,
    productLine: "LLEAP-HW",
    productName: "Laptop",
    serialNumber: "5CG7181CV5",
    assetName: "5CG7181CV5-Laptop",
    accountName: "Saint Joseph’s University",
    purchaseDate: "2017-06-13",
    installDate: "2017-06-16",
    assetWarrantyExpirationDate: "2018-06-15",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: ""
  },

  {
    id: 11,
    productLine: "MamaNatalie",
    productName: "MamaNatalie Complete (L)",
    serialNumber: "0",
    assetName: "0-MamaNatalie Complete (L)",
    accountName: "Saint Joseph’s University",
    purchaseDate: "2012-01-04",
    installDate: "2012-01-07",
    assetWarrantyExpirationDate: "2013-01-06",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: ""
  },

  {
    id: 12,
    productLine: "MegaCode Kid",
    productName: "MegaCode Kid (L)",
    serialNumber: "231M04090010",
    assetName: "231M04090010-MegaCode Kid (L)",
    accountName: "Saint Joseph’s University",
    purchaseDate: "2009-01-07",
    installDate: "2009-01-08",
    assetWarrantyExpirationDate: "2010-01-07",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: ""
  },

  {
    id: 13,
    productLine: "Nursing Anne",
    productName: "Nursing Anne Manikin Light",
    serialNumber: "325M24080021",
    assetName: "325M24080021-Nursing Anne (L)",
    accountName: "Saint Joseph’s University",
    purchaseDate: "2008-06-04",
    installDate: "2008-06-05",
    assetWarrantyExpirationDate: "2009-06-04",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: ""
  },

  {
    id: 14,
    productLine: "Nursing Anne",
    productName: "Nursing Anne Manikin Light",
    serialNumber: "325M24080022",
    assetName: "325M24080022-Nursing Anne (L)",
    accountName: "Saint Joseph’s University",
    purchaseDate: "2008-06-04",
    installDate: "2008-06-05",
    assetWarrantyExpirationDate: "2009-06-04",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: ""
  },

  {
    id: 15,
    productLine: "Nursing Anne",
    productName: "Nursing Anne Manikin Light",
    serialNumber: "325M04090010",
    assetName: "325M04090010-Nursing Anne (L)",
    accountName: "Saint Joseph’s University",
    purchaseDate: "2009-01-07",
    installDate: "2009-01-08",
    assetWarrantyExpirationDate: "2010-01-07",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: "Room 2152 OR / Cardiac",
    image: "inven_15.jpg",
  },

  {
    id: 16,
    productLine: "Nursing Anne",
    productName: "Nursing Anne Manikin Dark",
    serialNumber: "325UMB4819013",
    assetName: "325UMB4819013-Nursing Anne (D)",
    accountName: "Saint Joseph’s University",
    purchaseDate: "2020-02-12",
    installDate: "",
    assetWarrantyExpirationDate: "2021-02-11",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: ""
  },

  {
    id: 17,
    productLine: "Nursing Anne Simulator",
    productName: "Nursing Anne Simulator Medium",
    serialNumber: "320UMM0621003",
    assetName: "320UMM0621003-Nursing Anne Simulator Medium",
    accountName: "Saint Joseph’s University",
    purchaseDate: "2021-02-19",
    installDate: "2021-05-04",
    assetWarrantyExpirationDate: "2022-05-03",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: "Room 2355 ICU I",
    image: "inven_17.jpg"
  },

  {
    id: 18,
    productLine: "Nursing Anne Simulator",
    productName: "Nursing Anne Simulator Dark",
    serialNumber: "320UMD4521002",
    assetName: "320UMD4521002-Nursing Anne Simulator-D",
    accountName: "Saint Joseph’s University",
    purchaseDate: "2021-12-15",
    installDate: "",
    assetWarrantyExpirationDate: "2022-12-14",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: "Room 2355 ICU I",
    image: "inven_18.jpg"
  },

  {
    id: 19,
    productLine: "PROMPT Birthing",
    productName: "PROMPT Birthing Simulator Force",
    serialNumber: "0",
    assetName: "0-PROMPT Birthing Simulator Force",
    accountName: "Saint Joseph’s University",
    purchaseDate: "2010-06-25",
    installDate: "2013-01-10",
    assetWarrantyExpirationDate: "2014-01-09",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: ""
  },

  {
    id: 20,
    productLine: "Resusci Anne QCPR AED",
    productName: "Resusci Anne QCPR AED Torso - Rechargeable",
    serialNumber: "1734423021",
    assetName: "1734423021-Resusci Anne QCPR AED Torso - Rechargeable",
    accountName: "Saint Joseph’s University",
    purchaseDate: "2023-11-06",
    installDate: "",
    assetWarrantyExpirationDate: "",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: ""
  },

  {
    id: 21,
    productLine: "Resusci Anne QCPR AED",
    productName: "Resusci Anne QCPR AED Torso - Rechargeable",
    serialNumber: "1734423024",
    assetName: "1734423024-Resusci Anne QCPR AED Torso - Rechargeable",
    accountName: "Saint Joseph’s University",
    purchaseDate: "2023-11-06",
    installDate: "",
    assetWarrantyExpirationDate: "",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: ""
  },

  {
    id: 22,
    productLine: "Resusci Baby QCPR",
    productName: "Resusci Baby QCPR",
    serialNumber: "4016",
    assetName: "4016-Resusci Baby QCPR",
    accountName: "Saint Joseph’s University",
    purchaseDate: "2017-01-10",
    installDate: "2017-01-11",
    assetWarrantyExpirationDate: "2018-01-10",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: ""
  },

  {
    id: 23,
    productLine: "Resusci Baby QCPR",
    productName: "Resusci Baby QCPR",
    serialNumber: "1717",
    assetName: "1717-Resusci Baby QCPR",
    accountName: "Saint Joseph’s University",
    purchaseDate: "2017-06-13",
    installDate: "2017-06-16",
    assetWarrantyExpirationDate: "2018-06-15",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: ""
  },

  {
    id: 24,
    productLine: "Resusci Baby QCPR",
    productName: "Resusci Baby QCPR",
    serialNumber: "2317",
    assetName: "2317-Resusci Baby QCPR",
    accountName: "Saint Joseph’s University",
    purchaseDate: "2017-08-01",
    installDate: "2017-08-02",
    assetWarrantyExpirationDate: "2018-08-01",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: ""
  },

  {
    id: 25,
    productLine: "SimBaby",
    productName: "SimBaby (US) Manikin + Link Box",
    serialNumber: "245151603237",
    assetName: "245151603237-SimBaby (US) Manikin + Link Box",
    accountName: "Saint Joseph’s University",
    purchaseDate: "2016-05-06",
    installDate: "2016-08-01",
    assetWarrantyExpirationDate: "2017-07-31",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: ""
  },

  {
    id: 26,
    productLine: "SimJunior",
    productName: "SimJr Adv w/Cpl P-Kit-US Mkn, VSim, PC, Mntr (S)",
    serialNumber: "232M01120021",
    assetName: "232M01120021-SimJr Adv w/Cpl P-Kit-US Mkn, VSim, PC, Mntr (S)",
    accountName: "Saint Joseph’s University",
    purchaseDate: "2012-01-04",
    installDate: "2012-01-17",
    assetWarrantyExpirationDate: "2013-01-16",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: ""
  },

  {
    id: 27,
    productLine: "SimMan 3G",
    productName: "SimMan 3G (US) Light Manikin and accessories",
    serialNumber: "21207154471",
    assetName: "21207154471-SimMan 3G (US) Light Manikin and accessories",
    accountName: "Saint Joseph’s University",
    purchaseDate: "2015-04-29",
    installDate: "2019-12-05",
    assetWarrantyExpirationDate: "2020-12-04",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: "Room 2356 ICU II",
    image: "inven_27.jpg"
  },

  {
    id: 28,
    productLine: "SimMan ALS",
    productName: "SimMan ALS (US)Manikin and Accessories",
    serialNumber: "23521160201",
    assetName: "23521160201-SimMan ALS (US)Manikin and Accessories",
    accountName: "Saint Joseph’s University",
    purchaseDate: "2016-05-06",
    installDate: "2016-07-26",
    assetWarrantyExpirationDate: "2017-07-25",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: "Room 2356 ICU II",
    image: "inven_28.jpg",
  },

  {
    id: 29,
    productLine: "SimNewB",
    productName: "SIMNEWB STD W/COMP",
    serialNumber: "220M49100004",
    assetName: "220M49100004-SIMNEWB STD W/COMP",
    accountName: "Saint Joseph’s University",
    purchaseDate: "2010-11-23",
    installDate: "2010-12-09",
    assetWarrantyExpirationDate: "2011-12-08",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: ""
  },

  {
    id: 30,
    productLine: "SimNewB",
    productName: "SIMNEWB STD W/COMP",
    serialNumber: "220M29090002",
    assetName: "220M29090002-SIMNEWB STD W/COMP",
    accountName: "Saint Joseph’s University",
    purchaseDate: "2009-06-22",
    installDate: "2009-07-20",
    assetWarrantyExpirationDate: "2010-07-19",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: ""
  },

  {
    id: 31,
    productLine: "SimPad",
    productName: "SimPad Trade In-US",
    serialNumber: "ZW1231000904",
    assetName: "ZW1231000904-SimPad Trade In-US",
    accountName: "Saint Joseph’s University",
    purchaseDate: "2012-03-09",
    installDate: "2012-06-20",
    assetWarrantyExpirationDate: "2013-06-19",
    quantity: 1,
    assetOwnership: "Customer owned",
    location: "",
    },
      {
    id: 32,
    productLine: "SimPad",
    productName: "SimPad Trade In-US",
    serialNumber: "ZW1231000913",
    assetName: "ZW1231000913-SimPad Trade In-US",
    accountName: "Saint Joseph’s University",
    purchaseDate: "2012-03-09",
    installDate: "2012-06-20",
    assetWarrantyExpirationDate: "2013-06-19",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: ""
  },
  {
    id: 33,
    productLine: "SimPad",
    productName: "SimPad Trade In-US",
    serialNumber: "ZW1231001006",
    assetName: "ZW1231001006-SimPad Trade In-US",
    accountName: "Saint Joseph’s University",
    purchaseDate: "2012-03-09",
    installDate: "2012-06-20",
    assetWarrantyExpirationDate: "2013-06-19",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: ""
  },
  {
    id: 34,
    productLine: "SimPad",
    productName: "SimPad Trade In-US",
    serialNumber: "ZW1231001010",
    assetName: "ZW1231001010-SimPad Trade In-US",
    accountName: "Saint Joseph’s University",
    purchaseDate: "2012-03-09",
    installDate: "2012-06-20",
    assetWarrantyExpirationDate: "2013-06-19",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: ""
  },
  {
    id: 35,
    productLine: "SimPad",
    productName: "SimPad Trade In-US",
    serialNumber: "ZW1231000810",
    assetName: "ZW1231000810-SimPad Trade In-US",
    accountName: "Saint Joseph’s University",
    purchaseDate: "2012-03-12",
    installDate: "2012-06-21",
    assetWarrantyExpirationDate: "2013-06-20",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: ""
  },
  {
    id: 36,
    productLine: "SimPad",
    productName: "SimPad Trade In-US",
    serialNumber: "ZW1231000912",
    assetName: "ZW1231000912-SimPad Trade In-US",
    accountName: "Saint Joseph’s University",
    purchaseDate: "2012-03-12",
    installDate: "2012-06-21",
    assetWarrantyExpirationDate: "2013-06-20",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: ""
  },
  {
    id: 37,
    productLine: "SimPad",
    productName: "SimPad Trade In-US",
    serialNumber: "ZW1231001007",
    assetName: "ZW1231001007-SimPad Trade In-US",
    accountName: "Saint Joseph’s University",
    purchaseDate: "2012-03-12",
    installDate: "2012-06-21",
    assetWarrantyExpirationDate: "2013-06-20",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: ""
  },
  {
    id: 38,
    productLine: "SimPad",
    productName: "SimPad Trade In-US",
    serialNumber: "ZW1240000033",
    assetName: "ZW1240000033-SimPad Trade In-US",
    accountName: "Saint Joseph’s University",
    purchaseDate: "2012-03-12",
    installDate: "2012-06-21",
    assetWarrantyExpirationDate: "2013-06-20",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: ""
  },
  {
    id: 39,
    productLine: "SimPad",
    productName: "SimPad Trade In-US",
    serialNumber: "ZW1231000746",
    assetName: "ZW1231000746-SimPad Trade In-US",
    accountName: "Saint Joseph’s University",
    purchaseDate: "2012-05-31",
    installDate: "2012-06-21",
    assetWarrantyExpirationDate: "2013-06-20",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: ""
  },
  {
    id: 40,
    productLine: "SimPad",
    productName: "SimPad Trade In-US",
    serialNumber: "ZW1240000028",
    assetName: "ZW1240000028-SimPad Trade In-US",
    accountName: "Saint Joseph’s University",
    purchaseDate: "2012-05-31",
    installDate: "2012-06-21",
    assetWarrantyExpirationDate: "2013-06-20",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: ""
  },
  {
    id: 41,
    productLine: "SimPad",
    productName: "SimPad Trade In-US",
    serialNumber: "ZW1260011112",
    assetName: "ZW1260011112-SimPad Trade In-US",
    accountName: "Saint Joseph’s University",
    purchaseDate: "2012-08-03",
    installDate: "2012-09-12",
    assetWarrantyExpirationDate: "2013-09-11",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: ""
  },
  {
    id: 42,
    productLine: "SimPad Plus",
    productName: "SimPad PLUS Only (US)",
    serialNumber: "TSBG06023431",
    assetName: "TSBG06023431-SimPad PLUS Only (US)",
    accountName: "Saint Joseph’s University",
    purchaseDate: "2016-11-02",
    installDate: "2016-11-03",
    assetWarrantyExpirationDate: "2017-11-02",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: ""
  },
    {
    id: 43,
    productLine: "Nasco Healthcare",
    productName: "Veinpuncture and Injection training arm",
    serialNumber: "",
    assetName: "",
    accountName: "Saint Joseph’s University",
    purchaseDate: "",
    installDate: "",
    assetWarrantyExpirationDate: "",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: "Control Room rack"
  },
      {
    id: 44,
    productLine: "Life Form",
    productName: "Veinpuncture and Injection training arm",
    serialNumber: "",
    assetName: "",
    accountName: "Saint Joseph’s University",
    purchaseDate: "",
    installDate: "",
    assetWarrantyExpirationDate: "",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: "Control Room rack"
  },
      {
    id: 45,
    productLine: "Laerdal",
    productName: "Adult Male Left Arm",
    serialNumber: "",
    assetName: "",
    accountName: "Saint Joseph’s University",
    purchaseDate: "",
    installDate: "",
    assetWarrantyExpirationDate: "",
    quantity: 2,
    assetOwnership: "Customer Owned",
    location: "Room 2355 ICU I"
  },
  {
    id: 46,
    productLine: "Laerdal",
    productName: "SimJuniour Advanced Manikin",
    serialNumber: "232UMB1615007",
    assetName: "Bobby Dark",
    accountName: "Saint Joseph’s University",
    purchaseDate: "",
    installDate: "",
    assetWarrantyExpirationDate: "",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: "Control Room rack",
    image: "inven_46.jpg"
  },
    {
    id: 47,
    productLine: "Vata",
    productName: " Seymour II wound care model 0910 ",
    serialNumber: "5036515050",
    assetName: "Seymour II Wound Care Model, Lightly Pigmented",
    accountName: "Saint Joseph’s University",
    purchaseDate: "",
    installDate: "",
    assetWarrantyExpirationDate: "",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: "Skills Lab",
    image: "inven_47.jpg"
  },
      {
    id: 48,
    productLine: "Gaumard Scientific",
    productName: "Gaumard 5 year old pediatric Sim Manikin",
    serialNumber: "305-971-3790",
    assetName: "Seymour II Wound Care Model, Lightly Pigmented",
    accountName: "Saint Joseph’s University",
    purchaseDate: "",
    installDate: "",
    assetWarrantyExpirationDate: "",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: "Manikin Rack",
    image: "inven_48.jpg"
  },
    {
    id: 49,
    productLine: "Gaumard Scientific",
    productName: "Gaumard SIMA Female static Manikin",
    serialNumber: "none",
    assetName: "Kathy Plastic",
    accountName: "Saint Joseph’s University",
    purchaseDate: "",
    installDate: "",
    assetWarrantyExpirationDate: "",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: "Manikin Rack",
    image: "inven_49.jpg"
  },
      {
    id: 50,
    productLine: "Gaumard Scientific",
    productName: "Gaumard SIMA Female static Manikin",
    serialNumber: "none",
    assetName: "Debra Simson",
    accountName: "Saint Joseph’s University",
    purchaseDate: "",
    installDate: "",
    assetWarrantyExpirationDate: "",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: "Manikin Rack",
    image: "inven_50.jpg"
  },
    {
    id: 51,
    productLine: "Gaumard Scientific",
    productName: "Gaumard SIMA Female static Manikin",
    serialNumber: "none",
    assetName: "Susie Latex",
    accountName: "Saint Joseph’s University",
    purchaseDate: "",
    installDate: "",
    assetWarrantyExpirationDate: "",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: "Manikin Rack",
    image: "inven_51.jpg"
  },
  {
    id: 52,
    productLine: "Gaumard Scientific",
    productName: "Gaumard SIMA Female static Manikin",
    serialNumber: "none",
    assetName: "Chloe Latex",
    accountName: "Saint Joseph’s University",
    purchaseDate: "",
    installDate: "",
    assetWarrantyExpirationDate: "",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: "Manikin Rack",
    image: "inven_52.jpg"
  },
  {
    id: 53,
    productLine: "Gaumard",
    productName: "Susie Care Simulator with Ostomy Medium static Manikin",
    serialNumber: "none",
    assetName: "Emily Write",
    accountName: "Saint Joseph’s University",
    purchaseDate: "",
    installDate: "",
    assetWarrantyExpirationDate: "",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: "Manikin Rack",
    image: "inven_53.jpg"
  },
    {
    id: 54,
    productLine: "Gaumard",
    productName: "Susie Care Simulator with Ostomy Medium static Manikin",
    serialNumber: "none",
    assetName: "Shelly Thompson",
    accountName: "Saint Joseph’s University",
    purchaseDate: "",
    installDate: "",
    assetWarrantyExpirationDate: "",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: "Manikin Rack",
    image: "inven_54.jpg"
  },
    {
    id: 55,
    productLine: "Gaumard Scientific",
    productName: "Gaumard SIMA Female static Manikin",
    serialNumber: "none",
    assetName: "Tammy Wilde",
    accountName: "Saint Joseph’s University",
    purchaseDate: "",
    installDate: "",
    assetWarrantyExpirationDate: "",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: "Manikin Rack",
    image: "inven_55.jpg"
  },
    {
    id: 56,
    productLine: "Gaumard",
    productName: "Susie Care Simulator with Ostomy Dark static Manikin",
    serialNumber: "none",
    assetName: "Regina Hall",
    accountName: "Saint Joseph’s University",
    purchaseDate: "",
    installDate: "",
    assetWarrantyExpirationDate: "",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: "Manikin Rack",
    image: "inven_56.jpg"
  },
  {
    id: 57,
    productLine: "Gaumard",
    productName: "Susie Care Simulator with Ostomy Medium static Manikin",
    serialNumber: "none",
    assetName: "Regina Hall",
    accountName: "Saint Joseph’s University",
    purchaseDate: "",
    installDate: "",
    assetWarrantyExpirationDate: "",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: "Room 2355 ICU I",
    image: "inven_57.jpg"
  },
    {
    id: 58,
    productLine: "Gaumard",
    productName: "Susie Care Simulator with Ostomy Medium static Manikin",
    serialNumber: "none",
    assetName: "Regina Hall",
    accountName: "Saint Joseph’s University",
    purchaseDate: "",
    installDate: "",
    assetWarrantyExpirationDate: "",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: "Room 2252 Clinical Skills Practice Lab",
    image: "inven_58.jpg"
  },
      {
    id: 59,
    productLine: "Medical Plastics Laboratory INC",
    productName: "ND-Series Multi-Nursing Patient Care Simulator Manikin",
    serialNumber: "none",
    assetName: "Walker Texas",
    accountName: "Saint Joseph’s University",
    purchaseDate: "",
    installDate: "",
    assetWarrantyExpirationDate: "",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: "Room 2252 Clinical Skills Practice Lab",
    image: "inven_59.jpg"
  },
  {
    id: 60,
    productLine: "Gaumard",
    productName: "Susie Care Simulator with Ostomy Dark static Manikin",
    serialNumber: "none",
    assetName: "Stacy Martin",
    accountName: "Saint Joseph’s University",
    purchaseDate: "",
    installDate: "",
    assetWarrantyExpirationDate: "",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: "Room 2251 Clinical Skills Lab I",
    image: "inven_60.jpg"
  },
    {
    id: 61,
    productLine: "Gaumard",
    productName: "Susie Care Simulator with Ostomy Dark static Manikin",
    serialNumber: "none",
    assetName: "Rachel Martin",
    accountName: "Saint Joseph’s University",
    purchaseDate: "",
    installDate: "",
    assetWarrantyExpirationDate: "",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: "Room 2251 Clinical Skills Lab I",
    image: "inven_61.jpg"
  },
    {
    id: 62,
    productLine: "Gaumard",
    productName: "Susie Care Simulator with Ostomy Medium static Manikin",
    serialNumber: "none",
    assetName: "Laura Evans",
    accountName: "Saint Joseph’s University",
    purchaseDate: "",
    installDate: "",
    assetWarrantyExpirationDate: "",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: "Room 2251 Clinical Skills Lab I",
    image: "inven_62.jpg"
  },
    {
    id: 63,
    productLine: "Life/Form",
    productName: "Tracheostomy Care Simulator",
    serialNumber: "LF1159-1107",
    assetName: "Head and upper torso task-trainer",
    accountName: "Saint Joseph’s University",
    purchaseDate: "",
    installDate: "",
    assetWarrantyExpirationDate: "",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: "Respiratory Theropy Room 2150",
    image: "inven_63.jpg"
  },
  {
    id: 64,
    productLine: "Laerdal Medical",
    productName: "Airway Management Trainer",
    serialNumber: "LF1159-1107",
    assetName: "Head and upper torso task-trainer",
    accountName: "Saint Joseph’s University",
    purchaseDate: "",
    installDate: "",
    assetWarrantyExpirationDate: "",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: "Respiratory Theropy Room 2150",
    image: "inven_64.jpg"
  },
    {
    id: 65,
    productLine: "Laerdal Medical",
    productName: "Airway Management Trainer",
    serialNumber: "LF1159-1107",
    assetName: "Head and upper torso task-trainer",
    accountName: "Saint Joseph’s University",
    purchaseDate: "",
    installDate: "",
    assetWarrantyExpirationDate: "",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: "Respiratory Theropy Room 2150",
    image: "inven_65.jpg"
  },
    { 
    id: 66,
    productLine: "Nursing Anne",
    productName: "Nursing Anne Manikin Light",
    serialNumber: "325UMT0815019",
    assetName: "325M24080021-Nursing Anne (M)",
    accountName: "Saint Joseph’s University",
    purchaseDate: "",
    installDate: "",
    assetWarrantyExpirationDate: "",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: "Respiratory Therapy Room 2150",
    image: "inven_66.jpg",
  },
  { 
    id: 67,
    productLine: "Hospira",
    productName: "Plum A+ IV",
    serialNumber: "17759972",
    assetName: "Hospira Plum A+ ver. 13.43.00.001",
    accountName: "Saint Joseph’s University",
    purchaseDate: "",
    installDate: "",
    assetWarrantyExpirationDate: "",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: "Class Room 1430",
    image: "inven_67.jpg",
    status: "working"
  },
  { 
    id: 68,
    productLine: "Hospira",
    productName: "Plum A+ IV",
    serialNumber: "14104736",
    assetName: "Hospira Plum A+ ver. 13.42.00.002",
    accountName: "Saint Joseph’s University",
    purchaseDate: "",
    installDate: "",
    assetWarrantyExpirationDate: "",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: "Class Room 1430",
    image: "inven_68.jpg",
    status: "working"
  },
    { 
    id: 69,
    productLine: "Hospira",
    productName: "Plum A+ IV",
    serialNumber: "13940819E",
    assetName: "Hospira Plum A+ ver. 13.42.00.002",
    accountName: "Saint Joseph’s University",
    purchaseDate: "",
    installDate: "",
    assetWarrantyExpirationDate: "",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: "Class Room 1430",
    image: "inven_69.jpg",
    status: "working"
  },
  { 
    id: 70,
    productLine: "Hospira",
    productName: "Plum A+ IV",
    serialNumber: "03975579",
    assetName: "Hospira Plum A+ ver. 13.40.00.006",
    accountName: "Saint Joseph’s University",
    purchaseDate: "",
    installDate: "",
    assetWarrantyExpirationDate: "",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: "Class Room 1430",
    image: "inven_70.jpg",
    status: "working"
  },
    { 
    id: 71,
    productLine: "Hospira",
    productName: "Plum A+ IV",
    serialNumber: "14123554",
    assetName: "Hospira Plum A+ ver. E11.60",
    accountName: "Saint Joseph’s University",
    purchaseDate: "",
    installDate: "",
    assetWarrantyExpirationDate: "",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: "Class Room 1430",
    image: "inven_71.jpg",
    status: "working"
  },
  { 
    id: 72,
    productLine: "Hospira",
    productName: "Plum A+ IV",
    serialNumber: "13841904",
    assetName: "Hospira Plum A+ ver. E11.60",
    accountName: "Saint Joseph’s University",
    purchaseDate: "",
    installDate: "",
    assetWarrantyExpirationDate: "",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: "Class Room 1430",
    image: "inven_72.jpg",
    status: "working"
  },
  { 
    id: 73,
    productLine: "Hospira",
    productName: "Plum A+ IV",
    serialNumber: "15458059",
    assetName: "Hospira Plum A+ ver. 13.40.00.006",
    accountName: "Saint Joseph’s University",
    purchaseDate: "",
    installDate: "",
    assetWarrantyExpirationDate: "",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: "Class Room 1430",
    image: "inven_73.jpg",
    status: "working"
  },
  { 
    id: 74,
    productLine: "Hospira",
    productName: "Plum A+ IV",
    serialNumber: "17601422",
    assetName: "Hospira Plum A+ ver. 13.41.00.002",
    accountName: "Saint Joseph’s University",
    purchaseDate: "",
    installDate: "",
    assetWarrantyExpirationDate: "",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: "Class Room 1430",
    image: "inven_74.jpg",
    status: "working"
  },
  { 
    id: 75,
    productLine: "Hospira",
    productName: "Plum A+ IV",
    serialNumber: "17443355",
    assetName: "Hospira Plum A+ ver. E11.60",
    accountName: "Saint Joseph’s University",
    purchaseDate: "",
    installDate: "",
    assetWarrantyExpirationDate: "",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: "Class Room 1430",
    image: "inven_75.jpg",
    status: "working"
  },
  { 
    id: 76,
    productLine: "Hospira",
    productName: "Plum A+ IV",
    serialNumber: "1746690",
    assetName: "Hospira Plum A+ ver. E11.60",
    accountName: "Saint Joseph’s University",
    purchaseDate: "",
    installDate: "",
    assetWarrantyExpirationDate: "",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: "Class Room 1430",
    image: "inven_76.jpg",
    status: "working"
  },
    { 
    id: 77,
    productLine: "Alaris",
    productName: "Alaris PC Point-of-Care Unit",
    serialNumber: "1746690",
    assetName: "Alaris PCU IV Model 8015",
    accountName: "Saint Joseph’s University",
    purchaseDate: "",
    installDate: "",
    assetWarrantyExpirationDate: "",
    quantity: 1,
    assetOwnership: "Customer Owned",
    location: "Class Room 1430",
    image: "inven_77.jpg",
    status: "working"
  },
  {
  "id": 78,
  "productLine": "Geri",
  "productName": "Geri TM Nasco Geriatric Manikin",
  "serialNumber": "LF4030-604",
  "assetName": "LF4030-604-Geri Geriatric Manikin",
  "accountName": "Saint Joseph’s University",
  "purchaseDate": "",
  "installDate": "",
  "assetWarrantyExpirationDate": "",
  "quantity": 1,
  "assetOwnership": "Customer Owned",
  "location": "Simulation Lab",
  "image": "inven_78.jpg"
}
];
