// events.js
window.event_title = [
    {
        id: 0,
        title: "Future Health Leaders Summer Camp 2026",
        active: true,//is it the event on the user view
        cover_image: "event_0.jpg",
    }
];

window.sim_events = [
    {
        id: 1,
        event_id: 0,
        title: "Welcome, Small Groups, and Introductions",
        date: "2026-06-08",
        day: "Monday",
        start_time: "9:00 AM",
        end_time: "9:30 AM",
        sort_time: "09:00",
        location: "Multipurpose Room",
        category: "Welcome",
        description: "Welcome, small groups, and introductions.",
        lead: "Jess Gillis",
        equipment: [],
        notes: ""
    },
    {
        id: 2,
        event_id: 0,
        title: "Campus Tour",
        date: "2026-06-08",
        day: "Monday",
        start_time: "9:30 AM",
        end_time: "9:45 AM",
        sort_time: "09:30",
        location: "Campus",
        category: "Tour",
        description: "SJU student volunteer campus tour.",
        lead: "",
        equipment: [],
        notes: ""
    },
    {
        id: 3,
        event_id: 0,
        title: "Academic Excellence Session",
        date: "2026-06-08",
        day: "Monday",
        start_time: "9:45 AM",
        end_time: "10:30 AM",
        sort_time: "09:45",
        location: "Multipurpose Room",
        category: "Session",
        description: "Academic excellence session.",
        lead: "",
        equipment: [],
        notes: "Owner: Jim"
    },

    // PAGE 2 EVENTS

    {
        id: 7,
        event_id: 0,
        title: "Personality Type Exploration",
        date: "2026-06-08",
        day: "Monday",
        start_time: "1:30 PM",
        end_time: "2:30 PM",
        sort_time: "13:30",
        location: "Multipurpose Room",
        category: "Session",
        description: "Personality type exploration.",
        lead: "Maddie Greth",
        equipment: [],
        notes: ""
    },
    {
        id: 8,
        event_id: 0,
        title: "Sensory Lab",
        date: "2026-06-08",
        day: "Monday",
        start_time: "2:45 PM",
        end_time: "3:45 PM",
        sort_time: "14:45",
        location: "CPR Room upstairs",
        category: "Lab",
        description: "Sensory lab.",
        lead: "Melissa Snyder",
        equipment: [],
        notes: ""
    },
    {
        id: 9,
        event_id: 0,
        title: "Reflection and Wrap-up",
        date: "2026-06-08",
        day: "Monday",
        start_time: "3:45 PM",
        end_time: "4:00 PM",
        sort_time: "15:45",
        location: "Multipurpose Room",
        category: "Reflection",
        description: "Reflection and wrap-up.",
        lead: "Melissa Snyder",
        equipment: [],
        notes: ""
    },
    {
        id: 10,
        event_id: 0,
        title: "Caring and Compassion",
        date: "2026-06-09",
        day: "Tuesday",
        start_time: "1:30 PM",
        end_time: "2:30 PM",
        sort_time: "13:30",
        location: "Multipurpose Room",
        category: "Session",
        description: "Walk outside and animal visit.",
        lead: "Jess and Lynne",
        equipment: [],
        notes: "Critter Connection confirmed"
    },
    {
        id: 11,
        event_id: 0,
        title: "Moral Compass / Ethics",
        date: "2026-06-09",
        day: "Tuesday",
        start_time: "2:45 PM",
        end_time: "3:45 PM",
        sort_time: "14:45",
        location: "Multipurpose Room",
        category: "Session",
        description: "Moral compass and ethics session.",
        lead: "Sage Olnick and Chris Wagner",
        equipment: [],
        notes: ""
    },
    {
        id: 12,
        event_id: 0,
        title: "Reflection and Wrap-up",
        date: "2026-06-09",
        day: "Tuesday",
        start_time: "3:45 PM",
        end_time: "4:00 PM",
        sort_time: "15:45",
        location: "Multipurpose Room",
        category: "Reflection",
        description: "Reflection and wrap-up.",
        lead: "Sage and Chris",
        equipment: [],
        notes: ""
    },
    {
        id: 13,
        event_id: 0,
        title: "Careers in Healthcare",
        date: "2026-06-10",
        day: "Wednesday",
        start_time: "1:30 PM",
        end_time: "2:30 PM",
        sort_time: "13:30",
        location: "Rooms 1520 and 1490",
        category: "Panel",
        description: "Careers in healthcare with student panelists.",
        lead: "",
        equipment: [],
        notes: "Owner: Jim"
    },
    {
        id: 14,
        event_id: 0,
        title: "Emotional Intelligence",
        date: "2026-06-10",
        day: "Wednesday",
        start_time: "2:45 PM",
        end_time: "3:45 PM",
        sort_time: "14:45",
        location: "Multipurpose Room",
        category: "Session",
        description: "Emotional intelligence session.",
        lead: "Megan Ressler",
        equipment: [],
        notes: ""
    },
    {
        id: 15,
        event_id: 0,
        title: "Reflection and Wrap-up",
        date: "2026-06-10",
        day: "Wednesday",
        start_time: "3:45 PM",
        end_time: "4:00 PM",
        sort_time: "15:45",
        location: "Multipurpose Room",
        category: "Reflection",
        description: "Reflection and wrap-up.",
        lead: "Jim",
        equipment: [],
        notes: ""
    },
    {
        id: 16,
        event_id: 0,
        title: "Rotation 1",
        date: "2026-06-11",
        day: "Thursday",
        start_time: "1:30 PM",
        end_time: "2:15 PM",
        sort_time: "13:30",
        location: "Rooms 1520 and 1490",
        category: "Rotation",
        description: "Group A Lego Bot. Group B CDM.",
        lead: "Patty and Jess",
        equipment: [],
        notes: ""
    },
    {
        id: 17,
        event_id: 0,
        title: "Rotation 2",
        date: "2026-06-11",
        day: "Thursday",
        start_time: "2:15 PM",
        end_time: "3:00 PM",
        sort_time: "14:15",
        location: "Rooms 1520 and 1490",
        category: "Rotation",
        description: "Groups switch. Group B Lego Bot. Group A CDM.",
        lead: "Patty and Jess",
        equipment: [],
        notes: ""
    },
    {
        id: 18,
        event_id: 0,
        title: "Certificates, Photos, and Closing",
        date: "2026-06-11",
        day: "Thursday",
        start_time: "3:00 PM",
        end_time: "4:00 PM",
        sort_time: "15:00",
        location: "Multipurpose Room",
        category: "Closing",
        description: "Certificates, photos, and closing.",
        lead: "Jess Gillis and Everyone",
        equipment: [],
        notes: "Requested Hawk Presence"
    }
];