export let sounds  = [
    {
        id: 0,
        name: "Lung Pleural Friction",
        file: "sound_0.mp3",
        type: "Lung Breath",
    },
    {
        id: 1,
        name: "Lung Wheezing",
        file: "sound_1.mp3",
        type: "Lung Breath",
    },
    {
        id: 2,
        name: "Lung Normal Vesicular",
        file: "sound_2.mp3",
        type: "Lung Breath",
    },
    {
        id: 3,
        name: "Lung Inspiratory Stridor",
        file: "sound_3.mp3",
        type: "Lung Breath",
    },
    {
        id: 4,
        name: "Lung Coarse Crackles",
        file: "sound_4.mp3",
        type: "Lung Breath",
    },
    {
        id: 5,
        name: "Death Rattle",
        file: "sound_5.mp3",
        type: "Lung Breath",
    },
    {
        id: 6,
        name: "Agonal Breathing",
        file: "sound_6.mp3",
        type: "Lung Breath",
    },
    {
        id: 7,
        name: "Asthma Wheezing",
        file: "sound_7.mp3",
        type: "Lung Breath",
    },
    {
        id: 8,
        name: "Wheezing Cough",
        file: "sound_8.mp3",
        type: "Lung Breath",
    },
    {
        id: 9,
        name: "Compressed Audacity Crackles and Wheezes Bronchiectasis in Cystic Fibrosis",
        file: "sound_9.mp3",
        type: "Lung Breath",
    },
    {
        id: 10,
        name: "Breathing Vent",
        file: "sound_10.mp3",
        type: "Lung Breath",
    },
    {
        id: 11,
        name: "Heart Opeining Snap",
        file: "sound_11.mp3",
        type: "Heart",
    },
    {
        id: 12,
        name: "Heart Early Systolic Murmur",
        file: "sound_12.mp3",
        type: "Heart",
    },
    {
        id: 13,
        name: "Heart Late Systolic Murmur",
        file: "sound_13.mp3",
        type: "Heart",
    },
    {
        id: 14,
        name: "Heart Pansystolic Murmur",
        file: "sound_14.mp3",
        type: "Heart",
    },
    {
        id: 15,
        name: "Heart Normal Split Second",
        file: "sound_15.mp3",
        type: "Heart",
    },
    {
        id: 16,
        name: "Heart Normal Split S1",
        file: "sound_16.mp3",
        type: "Heart",
    },
    {
        id: 17,
        name: "Heart Normal Split S3",
        file: "sound_17.mp3",
        type: "Heart",
    },
    {
        id: 18,
        name: "Heart Normal Split S4",
        file: "sound_18.mp3",
        type: "Heart",
    },
    {
        id: 19,
        name: "Heart Ejection Click",
        file: "sound_19.mp3",
        type: "Heart",
    },
    {
        id: 20,
        name: "Heart Diastolic Rumble",
        file: "sound_20.mp3",
        type: "Heart",
    },
    {
        id: 21,
        name: "Baby Cooing",
        file: "sound_21.mp3",
        type: "Baby",
    },
    {
        id: 22,
        name: "Sick Baby Sound",
        file: "sound_11.mp3",
        type: "Baby",
    },
    {
        id: 23,
        name: "Compressed Audacity baby Lung Laryngomalacia Inspiratory Expiratory Stridor",
        file: "sound_23.mp3",
        type: "Baby",
    },
    {
        id: 24,
        name: "Croup Laryngotracheitis Stridor Barking Cough",
        file: "sound_24.mp3",
        type: "Baby",
    },
];